# Generated by Django 2.2.13 on 2020-07-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markettingpref',
            name='mailchimp_subscribed',
            field=models.NullBooleanField(),
        ),
    ]
