# Generated by Django 2.2.13 on 2020-07-10 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], default='billing', max_length=60)),
                ('adress_line_1', models.CharField(max_length=60)),
                ('adress_line_2', models.CharField(blank=True, max_length=60, null=True)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('postal_code', models.CharField(max_length=60)),
                ('country', models.CharField(default='India', max_length=60)),
                ('phone_no', models.CharField(max_length=60)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billings.BillingProfile')),
            ],
        ),
    ]
