# Generated by Django 2.2.13 on 2020-07-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='adress_line_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='adress_line_2',
            new_name='address_line_2',
        ),
    ]
